import { bootstrapApplication } from '@angular/platform-browser';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { AppComponent } from './app/app.component';
import { routes } from './app/app.routes';
import { authInterceptor } from './app/interceptors/auth.interceptor';
import { registerLocaleData } from '@angular/common';
import localeEs from '@angular/common/locales/es';
import { LOCALE_ID, provideZonelessChangeDetection } from '@angular/core';
import { provideIcons } from '@ng-icons/core';
import {
  lucideLayoutDashboard,
  lucidePalmtree,
  lucideClipboardList,
  lucideNetwork,
  lucideNewspaper,
  lucideUsers,
  lucideScale,
  lucideShieldCheck,
  lucideCalendarDays,
  lucideSettings,
  lucideLockKeyhole,
  lucideMenu,
  lucideX,
  lucideLogOut,
  lucideMegaphone,
  lucidePanelLeftClose,
  lucideHourglass,
  lucideHospital,
  lucideUser,
  lucideBarChart,
  lucideCheck,
  lucideArrowRight,
  lucideSparkles,
  lucideBookOpen,
  lucideInfo,
  lucideTriangleAlert,
  lucideLoaderCircle,
  lucideSearch,
  lucideShield,
  lucidePaperclip,
  lucideWrench,
  lucideClock,
  lucideTrash2,
  lucideArrowLeft,
  lucideFileEdit,
  lucideLightbulb,
  lucideMail,
  lucideSend,
  lucideKey,
  lucideFile,
  lucideDownload,
  lucideRefreshCw,
  lucideMessageSquare,
  lucideCamera,
  lucideImagePlus,
  lucideBan,
  lucideUserPlus,
  lucideBriefcase,
  lucideFolderOpen,
  lucideBuilding2,
  lucidePencil,
  lucideUpload,
  lucideFolder,
  lucideStethoscope,
  lucideHandshake,
  lucideThermometer,
  lucideAmbulance,
  lucideBaby,
  lucideBanknote,
  lucideFileText,
  lucideHome,
  lucideChevronLeft,
  lucideChevronRight,
  lucideLayoutGrid,
  lucideList,
  lucidePlus,
  lucideUserCog
} from '@ng-icons/lucide';

registerLocaleData(localeEs);

bootstrapApplication(AppComponent, {
  providers: [
    provideZonelessChangeDetection(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    { provide: LOCALE_ID, useValue: 'es' },
    provideIcons({
      lucideLayoutDashboard,
      lucidePalmtree,
      lucideClipboardList,
      lucideNetwork,
      lucideNewspaper,
      lucideUsers,
      lucideScale,
      lucideShieldCheck,
      lucideCalendarDays,
      lucideSettings,
      lucideLockKeyhole,
      lucideMenu,
      lucideX,
      lucideLogOut,
      lucideMegaphone,
      lucidePanelLeftClose,
      lucideHourglass,
      lucideHospital,
      lucideUser,
      lucideBarChart,
      lucideCheck,
      lucideArrowRight,
      lucideSparkles,
      lucideBookOpen,
      lucideInfo,
      lucideTriangleAlert,
      lucideLoaderCircle,
      lucideSearch,
      lucideShield,
      lucidePaperclip,
      lucideWrench,
      lucideClock,
      lucideTrash2,
      lucideArrowLeft,
      lucideFileEdit,
      lucideLightbulb,
      lucideMail,
      lucideSend,
      lucideKey,
      lucideFile,
      lucideDownload,
      lucideRefreshCw,
      lucideMessageSquare,
      lucideCamera,
      lucideImagePlus,
      lucideBan,
      lucideUserPlus,
      lucideBriefcase,
      lucideFolderOpen,
      lucideBuilding2,
      lucidePencil,
      lucideUpload,
      lucideFolder,
      lucideStethoscope,
      lucideHandshake,
      lucideThermometer,
      lucideAmbulance,
      lucideBaby,
      lucideBanknote,
      lucideFileText,
      lucideHome,
      lucideChevronLeft,
      lucideChevronRight,
      lucideLayoutGrid,
      lucideList,
      lucidePlus,
      lucideUserCog
    })
  ]
}).catch(err => console.error(err));
