"""Add_dynamic_form_fields_to_VacationRequest

Revision ID: a30ce94f44ca
Revises: c3a85c94f0b4
Create Date: 2026-01-19 10:14:23.797538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a30ce94f44ca'
down_revision: Union[str, None] = 'c3a85c94f0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_requests', sa.Column('causal_date', sa.Date(), nullable=True))
    op.add_column('vacation_requests', sa.Column('child_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vacation_requests', sa.Column('child_birthdate', sa.Date(), nullable=True))
    op.add_column('vacation_requests', sa.Column('telework_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation_requests', 'telework_percentage')
    op.drop_column('vacation_requests', 'child_birthdate')
    op.drop_column('vacation_requests', 'child_name')
    op.drop_column('vacation_requests', 'causal_date')
    # ### end Alembic commands ###
