"""Add_is_featured_to_PermissionPolicy

Revision ID: c3a85c94f0b4
Revises: 717f6bf1aeff
Create Date: 2026-01-19 09:59:31.918849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a85c94f0b4'
down_revision: Union[str, None] = '717f6bf1aeff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission_policies', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('permission_policies', 'reset_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'anual_calendario'::character varying"))
    op.alter_column('permission_policies', 'reset_month',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('permission_policies', 'reset_day',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('permission_policies', 'max_days_per_period',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('permission_policies', 'validity_window_value',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('permission_policies', 'validity_window_unit',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'months'::character varying"))
    op.alter_column('permission_policies', 'is_accumulable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('permission_policies', 'accumulable_years',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('permission_policies', 'travel_extension_days',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('permission_policies', 'is_public_dashboard',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('permission_policies', 'validity_months')
    op.drop_column('permission_policies', 'max_days_per_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission_policies', sa.Column('max_days_per_year', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('permission_policies', sa.Column('validity_months', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('permission_policies', 'is_public_dashboard',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('permission_policies', 'travel_extension_days',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('permission_policies', 'accumulable_years',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('permission_policies', 'is_accumulable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('permission_policies', 'validity_window_unit',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'months'::character varying"))
    op.alter_column('permission_policies', 'validity_window_value',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('permission_policies', 'max_days_per_period',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('permission_policies', 'reset_day',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('permission_policies', 'reset_month',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('permission_policies', 'reset_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'anual_calendario'::character varying"))
    op.drop_column('permission_policies', 'is_featured')
    # ### end Alembic commands ###
