"""add_parent_id_to_users

Revision ID: f794d554c1f9
Revises: a30ce94f44ca
Create Date: 2026-01-20 12:46:31.339626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f794d554c1f9'
down_revision: Union[str, None] = 'a30ce94f44ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_parent_id'), 'users', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_parent_id'), table_name='users')
    op.drop_column('users', 'parent_id')
    # ### end Alembic commands ###
